# Generated by Django 2.0.7 on 2018-07-04 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('symbol', models.CharField(max_length=3, unique=True)),
                ('ecb_rate', models.FloatField(default=1.0)),
            ],
        ),
    ]
